import type { Metadata } from "next";
import {
  Cairo,
  Noto_Sans,
  Noto_Sans_Arabic,
  Poppins,
  Roboto,
} from "next/font/google";
import "../globals.css";
import NavBar from "@/components/nav";
import { cn } from "@/lib/utils";
import useTextDirection from "@/hooks/useTextDirection";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const cairo = Noto_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const direction = useTextDirection(params.locale);
  return (
    <html
      lang={params.locale}
      dir={direction}
      className={cn(
        `${poppins.className}`,
        params.locale === "ar" && ` ${cairo.className}`
      )}
    >
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
